### ISSUE TITLE
Replace Architecture Image

### ISSUE THREAD

**Issue by acloudiator** [polycube-network/polycube#4]
We should replace the architecture Picture [1], with a new one (produced by more expert designers :) ).
Or at least, replace the polycube(logo) text with just polycube.

[1] https://github.com/polycube-network/polycube/blob/master/Documentation/images/polycube-archi.png

- Matteo

**Comment by mauriciovasquezbernal** [comment]
@frisso @mbertrone  is this solved by https://github.com/polycube-network/polycube/pull/162?

**Comment by frisso** [comment]
Solved by #162

**Comment by goldenrye** [comment]
The new architecture diagram is more implementation oriented clearly explains what's the major "physical" components in the system. I think may be we should consider another logical representation as a complementary so that user can understand the logical functionalities in the system, something like the diagram below (just for demo purpose),
![image](https://user-images.githubusercontent.com/16398268/61073913-4b635380-a3cb-11e9-9e2f-4857e8aafa95.png)

**Comment by frisso** [comment]
I like it, Jianwen. I can volunteer to change it.
