### ISSUE TITLE
Delay functions don't work in kernel ebpf function

### ISSUE THREAD

**Issue by arayu05** [polycube-network/polycube#411]
Hi Team,
This is little unrelated question from polycube. But since you are also researching/working on eBPF, so you might've encountered something. With that thought-
I wanted to ask that, I'm trying to generate delay in acknowledgement using eBPF program. This I'm running on tc hook for egress packets.
I'm running the python+c program using bcc.
 i tried mdelay/msleep/udelay etc functions with delay.h library in c, it gives me LLVM error that "Program using external function which can't be resolved".

Then I tried implementing sleep functionality :
 Taking 3 variables: 
tprev (which get the current time at starting of prog)
tnow(this gets current time as the loop starts and gets updates in each iteration with current time)
timer: this is the duration for which we want program to be delayed.
the while loop is: while((tnow - tprev) ≤ timer) 
but ebpf prog treat it as n infinite loop and gives error that infinite loop detected.
Whereas it's not an infinite loop.

Is there a way to introduce delay in Ack or delay in general in eBPF program and How?

**Comment by FedeParola** [comment]
Hi @arayu05,
trying to introduce a delay into an eBPF function goes against what an eBPF program should be.
eBPF programs should be as fast as possible, since they are executed with preemption disabled and the core they are running on can't be used until they terminate.
It might be possible to introduce a delay with a loop, maybe with some effort to make the verifier accept the code, but again this is a waste of resources and not the way an eBPF program is intended to be.
You should leverage the TC subsystem of the network stack to achieve this objective, for example have a look at this: https://www.pico.net/kb/how-can-i-simulate-delayed-and-dropped-packets-in-linux/

**Comment by arayu05** [comment]
Hi @FedeParola,
Thanks for your response. 
I'm checking  tc related operations for the same usecase.
